config/routes.rb
Rails.application.routes.draw do
  resources :humen
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/human.rb
class Human < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/humen_controller.rb
class HumenController < ApplicationController
  before_action :set_human, only: [:show, :edit, :update, :destroy]

  # GET /humen
  # GET /humen.json
  def index
    @humen = Human.all
  end

  # GET /humen/1
  # GET /humen/1.json
  def show
  end

  # GET /humen/new
  def new
    @human = Human.new
  end

  # GET /humen/1/edit
  def edit
  end

  # POST /humen
  # POST /humen.json
  def create
    @human = Human.new(human_params)

    respond_to do |format|
      if @human.save
        format.html { redirect_to @human, notice: 'Human was successfully created.' }
        format.json { render :show, status: :created, location: @human }
      else
        format.html { render :new }
        format.json { render json: @human.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /humen/1
  # PATCH/PUT /humen/1.json
  def update
    respond_to do |format|
      if @human.update(human_params)
        format.html { redirect_to @human, notice: 'Human was successfully updated.' }
        format.json { render :show, status: :ok, location: @human }
      else
        format.html { render :edit }
        format.json { render json: @human.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /humen/1
  # DELETE /humen/1.json
  def destroy
    @human.destroy
    respond_to do |format|
      format.html { redirect_to humen_url, notice: 'Human was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_human
      @human = Human.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def human_params
      params.require(:human).permit(:name, :number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/humen_helper.rb
module HumenHelper
end

app/views/humen/_form.html.erb
<%= form_with(model: human, local: true) do |form| %>
  <% if human.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(human.errors.count, "error") %> prohibited this human from being saved:</h2>

      <ul>
        <% human.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/humen/edit.html.erb
<h1>Editing Human</h1>

<%= render 'form', human: @human %>

<%= link_to 'Show', @human %> |
<%= link_to 'Back', humen_path %>

app/views/humen/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Humen</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @humen.each do |human| %>
      <tr>
        <td><%= human.name %></td>
        <td><%= human.number %></td>
        <td><%= link_to 'Show', human %></td>
        <td><%= link_to 'Edit', edit_human_path(human) %></td>
        <td><%= link_to 'Destroy', human, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Human', new_human_path %>

app/views/humen/new.html.erb
<h1>New Human</h1>

<%= render 'form', human: @human %>

<%= link_to 'Back', humen_path %>

app/views/humen/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @human.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @human.number %>
</p>

<%= link_to 'Edit', edit_human_path(@human) %> |
<%= link_to 'Back', humen_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>